# .github/actions/bump-image/action.yml
name: "Flux Image Tag Bumper"
description: "Updates image tags in Flux HelmRelease YAMLs using flux-helpers CLI"
inputs:
  file:
    description: "Path to the HelmRelease YAML file"
    required: true
  set:
    description: "Image update(s) in the form repo=version (newline-separated)"
    required: true
  dry-run:
    description: "Set to true to preview changes"
    required: false
    type: bool
    default: false

runs:
  using: "composite"
  steps:
    - name: Download CLI
      shell: bash
      run: |
        curl -sL https://github.com/pat-nel87/flux-helpers/releases/latest/download/flux-helpers -o flux-helpers
        chmod +x flux-helpers

    - name: Run tag bump
      run: |
        FILE="${{ inputs.file }}"
        SET_INPUT="${{ inputs.set }}"
        DRY_RUN=${{ inputs.dry-run }}

        echo "🔍 dry-run flag = $DRY_RUN"

        SET_ARGS=$(echo "$SET_INPUT" | while read -r line; do
          [[ "$line" =~ ^-- ]] && continue
          echo --set "$line"
        done)
        ./flux-helpers bump --file "$FILE" $SET_ARGS 
      shell: bash
